### ISSUE TITLE
ing ve base

### ISSUE THREAD

**Issue by VB10** [hakandl/turkish-dictionary#2]
https://github.com/hakandl/turkish-dictionary/blob/30d49b1cb64d90438c60131f8ef6b8093fda2c46/lib/feature/home/service/content_service.dart#L17

bu katmanin onune muhakkak bir layer koyup servislerini hatalarini tek bir yerden yonet ing yazmaayida unutma

**Comment by hakandl** [comment]
ing olmayan yerler duzeltildi
