### ISSUE TITLE
late final

### ISSUE THREAD

**Issue by VB10** [hakandl/turkish-dictionary#4]
https://github.com/hakandl/turkish-dictionary/blob/30d49b1cb64d90438c60131f8ef6b8093fda2c46/lib/feature/home/viewmodel/home_viewmodel.dart#L11

ilk dogrudan late vermene gerek yok deger veridgmiz icin ikincisi bu tarz hive islemlerini de ayri bir class yapalim oradan kurtaralim

**Comment by hakandl** [comment]
late kaldirildi ayri class konusunu da not aldim tesekkurler
