### ISSUE TITLE
static ve page contorller

### ISSUE THREAD

**Issue by VB10** [hakandl/turkish-dictionary#5]
https://github.com/hakandl/turkish-dictionary/blob/30d49b1cb64d90438c60131f8ef6b8093fda2c46/lib/feature/home/viewmodel/home_viewmodel.dart#L12
bunlar burada olmamali ki static hic olmalai bu viewda olmali ve gelen habere gore ekranda cizilmeli

**Comment by hakandl** [comment]
page controller tasindi
